### ISSUE TITLE
Matrix4.inverted constructor misuses ArgumentError

### ISSUE THREAD

**Issue by Hixie** [google/vector_math.dart#160]
```
No constructor 'ArgumentError' with matching arguments declared in class 'ArgumentError'.
NoSuchMethodError: incorrect number of arguments passed to method named 'ArgumentError'
Receiver: Type: class 'ArgumentError'
Tried calling: ArgumentError(Instance of 'Matrix4', "other", "Matrix cannot be inverted")
Found: ArgumentError([dynamic])

#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:188)
#1      Matrix4.Matrix4.inverted (.../packages/vector_math/lib/src/vector_math_64/matrix4.dart:206)
```

**Comment by johnmccutchan** [comment]
Fixed in 1.4.7.
